# Generated by Django 5.2.8 on 2026-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_itenscompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Aguardando Pagamento'), (3, 'Pago')], default=1),
        ),
    ]
